// Demo catalog: albums released under Creative Commons licences that allow streaming
// with attribution (CC BY) or without conditions (CC0), sourced from the Internet Archive.
// Each entry lists the archive item, the cover file and the exact audio file names.

const CC_BY_3 = { name: "CC BY 3.0", url: "https://creativecommons.org/licenses/by/3.0/" };
const CC_BY_4 = { name: "CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/" };
const CC0 = { name: "CC0 1.0", url: "https://creativecommons.org/publicdomain/zero/1.0/" };

export const CATALOG = [
	{
		identifier: "Directionless_EP-8295",
		title: "Directionless EP",
		artist: "Broke For Free",
		releaseYear: 2011,
		genre: "Electronic",
		license: CC_BY_3,
		cover: "Directionless_EP-8295.jpg",
		tracks: [
			["Broke_For_Free_-_01_-_Night_Owl.mp3", "Night Owl"],
			["Broke_For_Free_-_02_-_My_Always_Mood.mp3", "My Always Mood"],
			["Broke_For_Free_-_03_-_Day_Bird.mp3", "Day Bird"],
			["Broke_For_Free_-_04_-_My_Luck.mp3", "My Luck"],
			["Broke_For_Free_-_05_-_Mells_Parade.mp3", "Mell's Parade"],
			["Broke_For_Free_-_06_-_Only_Instrumental.mp3", "Only Instrumental"],
		],
	},
	{
		identifier: "BrokeForFreeLayers",
		title: "Layers",
		artist: "Broke For Free",
		releaseYear: 2012,
		genre: "Electronic",
		license: CC_BY_3,
		cover: "cover.jpg",
		tracks: [
			["Broke For Free - Layers - 01 As Colourful As Ever.mp3", "As Colourful As Ever"],
			["Broke For Free - Layers - 02 Knock Knock.mp3", "Knock Knock"],
			["Broke For Free - Layers - 03 Only Knows.mp3", "Only Knows"],
			["Broke For Free - Layers - 04 If.mp3", "If"],
			["Broke For Free - Layers - 05 Note Drop.mp3", "Note Drop"],
			["Broke For Free - Layers - 06 Murmur.mp3", "Murmur"],
			["BrokeForFree-Layers-07Spellbound.mp3", "Spellbound"],
			["BrokeForFree-Layers-10AYear.mp3", "A Year"],
		],
	},
	{
		identifier: "Crawford_Street-17897",
		title: "Crawford Street",
		artist: "Josh Woodward",
		releaseYear: 2005,
		genre: "Folk Rock",
		license: CC_BY_4,
		cover: "Crawford_Street-17897.jpg",
		tracks: [
			["Josh_Woodward_-_01_-_Fight_the_Sea.mp3", "Fight the Sea"],
			["Josh_Woodward_-_03_-_Cherry.mp3", "Cherry"],
			["Josh_Woodward_-_05_-_Cant_Take_Our_Love_Away.mp3", "Can't Take Our Love Away"],
			["Josh_Woodward_-_07_-_Big_Disco_Ball.mp3", "Big Disco Ball"],
			["Josh_Woodward_-_15_-_Swimming_to_Cambodia.mp3", "Swimming to Cambodia"],
			["Josh_Woodward_-_19_-_Hey_Ruth.mp3", "Hey Ruth"],
			["Josh_Woodward_-_23_-_Sundown.mp3", "Sundown"],
			["Josh_Woodward_-_27_-_Waiting_Takes_Time.mp3", "Waiting Takes Time"],
		],
	},
	{
		identifier: "The_Simple_Life_Part_2_1667-16369",
		title: "The Simple Life (Part 2)",
		artist: "Josh Woodward",
		releaseYear: 2008,
		genre: "Folk Rock",
		license: CC_BY_4,
		cover: "The_Simple_Life_Part_2_1667-16369.jpg",
		tracks: [
			["Josh_Woodward_-_01_-_Ships.mp3", "Ships"],
			["Josh_Woodward_-_03_-_Flutter_By_Butterfly.mp3", "Flutter By, Butterfly"],
			["Josh_Woodward_-_05_-_On_Brevity.mp3", "On Brevity"],
			["Josh_Woodward_-_07_-_Dont_Close_Your_Eyes.mp3", "Don't Close Your Eyes"],
			["Josh_Woodward_-_11_-_Shadows_in_the_Moonlight.mp3", "Shadows in the Moonlight"],
			["Josh_Woodward_-_15_-_Memorized.mp3", "Memorized"],
			["Josh_Woodward_-_17_-_The_Mission.mp3", "The Mission"],
			["Josh_Woodward_-_21_-_Afterglow.mp3", "Afterglow"],
		],
	},
	{
		identifier: "KaiEngelTheRun",
		title: "The Run",
		artist: "Kai Engel",
		releaseYear: 2017,
		genre: "Ambient",
		license: CC_BY_3,
		cover: "cover.jpg",
		tracks: [
			["Kai Engel - The Run - 01 Seeker.mp3", "Seeker"],
			["Kai Engel - The Run - 02 Run.mp3", "Run"],
			["Kai Engel - The Run - 03 Harbor.mp3", "Harbor"],
			["Kai Engel - The Run - 04 Imminence.mp3", "Imminence"],
			["Kai Engel - The Run - 05 Passages.mp3", "Passages"],
			["Kai Engel - The Run - 06 Scenery.mp3", "Scenery"],
			["Kai Engel - The Run - 07 Tumult.mp3", "Tumult"],
			["Kai Engel - The Run - 08 Chance.mp3", "Chance"],
			["Kai Engel - The Run - 09 Denouement.mp3", "Denouement"],
		],
	},
	{
		identifier: "Jazz_Sampler-9619",
		title: "Jazz Sampler",
		artist: "Kevin MacLeod",
		releaseYear: 2011,
		genre: "Jazz",
		license: CC_BY_3,
		cover: "Jazz_Sampler-9619.jpg",
		tracks: [
			["Kevin_MacLeod_-_As_I_Figure.mp3", "As I Figure"],
			["Kevin_MacLeod_-_Backed_Vibes_Clean.mp3", "Backed Vibes Clean"],
			["Kevin_MacLeod_-_Dances_and_Dames.mp3", "Dances and Dames"],
			["Kevin_MacLeod_-_Faster_Does_It.mp3", "Faster Does It"],
			["Kevin_MacLeod_-_I_Knew_a_Guy.mp3", "I Knew a Guy"],
			["Kevin_MacLeod_-_Night_on_the_Docks_-_Sax.mp3", "Night on the Docks (Sax)"],
			["Kevin_MacLeod_-_Off_to_Osaka.mp3", "Off to Osaka"],
		],
	},
	{
		identifier: "Monplaisir-RelaxingUkulele",
		title: "Relaxing Ukulele",
		artist: "Monplaisir",
		releaseYear: 2017,
		genre: "Acoustic",
		license: CC0,
		cover: "cover.jpg",
		tracks: [
			["Monplaisir - Relaxing Ukulele - 01 Red Hair, Blue Sky.mp3", "Red Hair, Blue Sky"],
			["Monplaisir - Relaxing Ukulele - 02 Sincere Love.mp3", "Sincere Love"],
			["Monplaisir - Relaxing Ukulele - 03 Time Gap.mp3", "Time Gap"],
			["Monplaisir - Relaxing Ukulele - 04 First.mp3", "First"],
			["Monplaisir - Relaxing Ukulele - 05 Stay Quiet.mp3", "Stay Quiet"],
			["Monplaisir - Relaxing Ukulele - 06 On the road, looking at your feet.mp3", "On the Road, Looking at Your Feet"],
			["Monplaisir - Relaxing Ukulele - 07 Floating Temple.mp3", "Floating Temple"],
			["Monplaisir - Relaxing Ukulele - 08 Hop.mp3", "Hop"],
		],
	},
	{
		identifier: "LoyaltyFreakMusic-INSTRUMENTALRBBEATSTOSINGORRAPON",
		title: "Instrumental R&B Beats to Sing or Rap On",
		artist: "Loyalty Freak Music",
		releaseYear: 2018,
		genre: "R&B",
		license: CC0,
		cover: "Loyalty_Freak_Music_-_INSTRUMENTAL_RB_BEATS_TO_SING_OR_RAP_ON_-_2018051541837121.jpg",
		tracks: [
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 01 Sunglasses.mp3", "Sunglasses"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 02 Friend to friend.mp3", "Friend to Friend"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 03 Sensual Melancholia.mp3", "Sensual Melancholia"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 05 The candle.mp3", "The Candle"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 06 Talk to me.mp3", "Talk to Me"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 09 Dancing Fool.mp3", "Dancing Fool"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 13 Harsh Love.mp3", "Harsh Love"],
			["Loyalty Freak Music - INSTRUMENTAL R&B BEATS TO SING OR RAP ON - 16 Hope and Love.mp3", "Hope and Love"],
		],
	},
	{
		identifier: "loyalty-freak-music-lofi-ambient-songs",
		title: "Lofi Ambient Songs",
		artist: "Loyalty Freak Music",
		releaseYear: 2021,
		genre: "Lo-fi",
		license: CC0,
		cover: "cover.jpg",
		tracks: [
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 01 Lack of Color - Drowning in your smile.mp3", "Drowning in Your Smile (Lack of Color)"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 02 Lack of Color - Dancing in the street.mp3", "Dancing in the Street (Lack of Color)"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 03 Lack of Color - Aeroplane.mp3", "Aeroplane (Lack of Color)"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 04 Lack of Color - I'm glad you are here with me.mp3", "I'm Glad You Are Here With Me (Lack of Color)"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 05 Crying those tears I've kept so long.mp3", "Crying Those Tears I've Kept So Long"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 07 I hope you're happy.mp3", "I Hope You're Happy"],
			["Loyalty Freak Music - LOFI AMBIENT SONGS ! - 08 Lack of Color - Sugar and coffee.mp3", "Sugar and Coffee (Lack of Color)"],
		],
	},
];
